
package com.cy.cyf.net.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PolicyEndorNoticeService", targetNamespace = "http://service.ccic.com/prpall/certinotice/intf", wsdlLocation = "http://127.0.0.1:8080/CYF/webservice/certiNotice?wsdl")
public class PolicyEndorNoticeService
    extends Service
{

    private final static URL POLICYENDORNOTICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/CYF/webservice/certiNotice?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        POLICYENDORNOTICESERVICE_WSDL_LOCATION = url;
    }

    public PolicyEndorNoticeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyEndorNoticeService() {
        super(POLICYENDORNOTICESERVICE_WSDL_LOCATION, new QName("http://service.ccic.com/prpall/certinotice/intf", "PolicyEndorNoticeService"));
    }

    /**
     * 
     * @return
     *     returns CertiNotice
     */
    @WebEndpoint(name = "CertiNotice")
    public CertiNotice getCertiNotice() {
        return (CertiNotice)super.getPort(new QName("http://service.ccic.com/prpall/certinotice/intf", "CertiNotice"), CertiNotice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CertiNotice
     */
    @WebEndpoint(name = "CertiNotice")
    public CertiNotice getCertiNotice(WebServiceFeature... features) {
        return (CertiNotice)super.getPort(new QName("http://service.ccic.com/prpall/certinotice/intf", "CertiNotice"), CertiNotice.class, features);
    }

}
