package com.cyf.demo.webservice.service.impl;

import javax.jws.WebService;

import org.springframework.stereotype.Repository;

import com.cyf.demo.webservice.service.common.ResponseHeadDTO;
import com.cyf.demo.webservice.service.dto.CertiNotice;
import com.cyf.demo.webservice.service.dto.CertiNoticeRequest;
import com.cyf.demo.webservice.service.dto.CertiNoticeResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@Repository("policyEndorNoticeService")
@WebService(endpointInterface="com.cyf.demo.webservice.service.dto.CertiNotice",name = "PolicyEndorNoticeService", targetNamespace = "http://service.ccic.com/prpall/certinotice/intf",serviceName="PolicyEndorNoticeService",portName="CertiNotice")
public class PolicyEndorNoticeService implements CertiNotice{

	@Override
	public CertiNoticeResponse certinotice(CertiNoticeRequest certiNoticeRequest) {
		System.out.println("请求数据:" + certiNoticeRequest.toString());
		CertiNoticeResponse resp = new CertiNoticeResponse();
		ResponseHeadDTO responseHead = new ResponseHeadDTO();
		resp.setResponseHead(responseHead);
		responseHead.setStatus(2);
		responseHead.setAppCode("0");
		responseHead.setAppMessage("操作成功");
		System.out.println("返回数据:" + resp);
		return resp;
	}

}
