
package com.cyf.demo.webservice.client.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CertiNotice", targetNamespace = "http://service.ccic.com/prpall/certinotice/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CertiNotice {


    /**
     * 
     * @param certiNoticeRequest
     * @return
     *     returns com.cyf.demo.webservice.client.dto.CertiNoticeResponse
     */
    @WebMethod(action = "/prpall/certinotice")
    @WebResult(name = "CertiNoticeResponse", targetNamespace = "http://service.ccic.com/prpall/certinotice/bean", partName = "CertiNoticeResponse")
    public CertiNoticeResponse certinotice(
        @WebParam(name = "CertiNoticeRequest", targetNamespace = "http://service.ccic.com/prpall/certinotice/bean", partName = "CertiNoticeRequest")
        CertiNoticeRequest certiNoticeRequest);

}
